{% set name = "ansys-tools-common" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_tools_common-{{ version }}.tar.gz
  sha256: 92765d82fc87d492339b8426b3c36008ac4067c1eca08d522656cca8f66be006

build:
  entry_points:
    - ansys-launcher = ansys.tools.local_product_launcher._cli:cli
    - save-ansys-path = ansys.tools.common.path.save:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }},<4.0
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - click >=8.1.3
    - platformdirs >=3.6
    - requests >=2.32.4
    - scooby >=0.5.12
    - typing_extensions >=4.5

test:
  imports:
    - ansys.tools.common
  commands:
    - pip check
    - save-ansys-path --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ansys/ansys-tools-common
  summary: A set of tools for PyAnsys libraries
  dev_url: https://github.com/ansys/ansys-tools-common
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlejandroFernandezLuces
    - RobPasMue
